### ISSUE TITLE
time data '2001_11' does not match format '%Y-%m-%d_%H'

### ISSUE THREAD

**Issue by liukaizhijia** [sftekin/spatio-temporal-weather-forecasting#2]
if I change the formatting to '%Y_%m', then they say '2000-01-28_15' does not match format '%Y_%m'

**Comment by sftekin** [comment]
Can you give more details? Where is it exactly you get this? My guess is you are trying to read .nc files. You need to first extract them using `DataCreator`. For example,

```
start_date = pd.to_datetime('2000-1-01')
end_date = pd.to_datetime('2001-12-31')

data_creator = DataCreator(start_date=start_date, end_date=end_date, **data_params)
weather_data = data_creator.create_data()

```
where you can get the `**data_params` from `config.py`. After that this will create a directory `data_dump` under `data` folder where each file will be `.npy`

**Comment by liukaizhijia** [comment]
Sure, when I create 'data_raw' in folder 'data' and put the 99 .nc files there, I run 'python run.py' and the output is as below:

Creating the weather data
Spatial cropping started
0.00%
4.17%
8.33%
12.50%
16.67%
20.83%
25.00%
29.17%
33.33%
37.50%
41.67%
45.83%
50.00%
54.17%
58.33%
62.50%
66.67%
70.83%
75.00%
79.17%
83.33%
87.50%
91.67%
95.83%
Traceback (most recent call last):
  File "/home/kai/miniconda3/lib/python3.8/site-packages/pandas/core/tools/datetimes.py", line 456, in _convert_listlike_datetimes
    values, tz = conversion.datetime_to_datetime64(arg)
  File "pandas/_libs/tslibs/conversion.pyx", line 350, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 80, in <module>
    run()
  File "run.py", line 41, in run
    weather_data = data_creator.create_data()
  File "/home/kai/Downloads/ieee_weather-master/data_creator.py", line 83, in create_data
    path_arr = self.__sort_files_by_date(paths=path_list)
  File "/home/kai/Downloads/ieee_weather-master/data_creator.py", line 115, in __sort_files_by_date
    date_df['dates'] = pd.to_datetime(
  File "/home/kai/miniconda3/lib/python3.8/site-packages/pandas/core/tools/datetimes.py", line 805, in to_datetime
    values = convert_listlike(arg._values, format)
  File "/home/kai/miniconda3/lib/python3.8/site-packages/pandas/core/tools/datetimes.py", line 460, in _convert_listlike_datetimes
    raise e
  File "/home/kai/miniconda3/lib/python3.8/site-packages/pandas/core/tools/datetimes.py", line 423, in _convert_listlike_datetimes
    result, timezones = array_strptime(
  File "pandas/_libs/tslibs/strptime.pyx", line 144, in pandas._libs.tslibs.strptime.array_strptime
ValueError: time data '2001_11' does not match format '%Y-%m-%d_%H' (match)

thanks!

**Comment by sftekin** [comment]
May you debug tell me what's the value that `weather_folder` took. The script should've created a `data_dump` folder inside data folder where each weather data is extracted according to its date in format '%Y-%m-%d_%H' e.g '2000-01-01_00'. The function `__get_file_paths` gets the file names inside `data_dump` and `__sort_files_by_date` sorts the files according to date.

**Comment by liukaizhijia** [comment]
No worry, I have fixed the issue. The reason is I incidentally put .nc files to data_dump folder earlier, and as I mentioned they should be put into folder 'data_raw', thanks!
