### ISSUE TITLE
ValueError: time data 'highres' does not match format '%Y-%m-%d_%H' (match)

### ISSUE THREAD

**Issue by HaiXiang-Zhao** [sftekin/spatio-temporal-weather-forecasting#7]
Specific content of error reporting：
Traceback (most recent call last):
  File "D:\anaconda\envs\pytorch\lib\site-packages\pandas\core\tools\datetimes.py", line 456, in _convert_listlike_datetimes
    values, tz = conversion.datetime_to_datetime64(arg)
  File "pandas\_libs\tslibs\conversion.pyx", line 350, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\spatio-temporal-weather-forecasting-master\run.py", line 32, in <module>
    run_highres(model_name="weather_model")
  File "D:\spatio-temporal-weather-forecasting-master\run.py", line 9, in run_highres
    train_test(experiment_params=experiment_params,
  File "D:\spatio-temporal-weather-forecasting-master\experimenter.py", line 44, in train_test
    weather_data = data_creator.create_data()
  File "D:\spatio-temporal-weather-forecasting-master\data_generation\data_creator.py", line 56, in create_data
    path_arr = self.sort_files_by_date(paths=path_list,
  File "D:\spatio-temporal-weather-forecasting-master\data_generation\data_creator.py", line 121, in sort_files_by_date
    date_df['dates'] = pd.to_datetime(
  File "D:\anaconda\envs\pytorch\lib\site-packages\pandas\core\tools\datetimes.py", line 805, in to_datetime
    values = convert_listlike(arg._values, format)
  File "D:\anaconda\envs\pytorch\lib\site-packages\pandas\core\tools\datetimes.py", line 460, in _convert_listlike_datetimes
    raise e
  File "D:\anaconda\envs\pytorch\lib\site-packages\pandas\core\tools\datetimes.py", line 423, in _convert_listlike_datetimes
    result, timezones = array_strptime(
  File "pandas\_libs\tslibs\strptime.pyx", line 144, in pandas._libs.tslibs.strptime.array_strptime
ValueError: time data 'highres' does not match format '%Y-%m-%d_%H' (match)

i have download the highres and weatherbench datasets and put it under the data directory. The locations should be:

highres --> data/data_dump weatherbench --> data/weatherbench

**Comment by HaiXiang-Zhao** [comment]
And I put the data in the "highres" file in the data-dump, which generated this error message

**Comment by Yumy86** [comment]
# if rebuild true we extract from nc files inside data_raw (only for high res data)
